# Generated by Django 3.1.5 on 2021-01-19 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_manager', '0003_auto_20210119_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='like',
        ),
        migrations.CreateModel(
            name='BooksLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by_user', to='book_manager.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_book', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'book')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='likes',
            field=models.ManyToManyField(related_name='liked_books', through='book_manager.BooksLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
