# Generated by Django 3.1.5 on 2021-01-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_manager', '0005_auto_20210119_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='likes',
            new_name='user_likes',
        ),
        migrations.AddField(
            model_name='book',
            name='like',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество лайков'),
        ),
    ]
